// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  fullsize: string;
  green: string;
  normal: string;
  normalsize: string;
  root: string;
  small: string;
  yellow: string;
}
export const cssExports: CssExports;
export default cssExports;
